[theme]
base                     = "light"
primaryColor             = "#E63329"
backgroundColor          = "#EDEAE5"
secondaryBackgroundColor = "#E5E2DC"
textColor                = "#2A2825"
font                     = "sans serif"
